include:
  - tailscale.yaml

services:
  caddy:
    image: ghcr.io/rahulsalvi/caddy:latest
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - NET_ADMIN
    depends_on:
      tailscale:
        condition: service_healthy
    network_mode: service:tailscale
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
