include:
  - tailscale.yaml

services:
  caddy:
    image: ghcr.io/rahulsalvi/caddy:latest
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    extends:
      file: tailscale-app-base.yaml
      service: tailscale-app-base

volumes:
  caddy_data:
  caddy_config:
