services:
  aws-backup:
    image: ghcr.io/rahulsalvi/docker-volume-backup:latest
    environment:
      BACKUP_COMPRESSION: zst
      AWS_S3_PATH: ${COMPOSE_PROJECT_NAME}
      AWS_S3_BUCKET_NAME: ${BACKUP_AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${BACKUP_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${BACKUP_AWS_SECRET_ACCESS_KEY}
      AGE_PASSPHRASE: ${BACKUP_AGE_PASSPHRASE}
      NOTIFICATION_URLS: ntfy://ntfy.ipn.rahulsalvi.com/backups
      NOTIFICATION_LEVEL: info
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    extends:
      file: tailscale-app-base.yaml
      service: tailscale-app-base

  aws-backup-frequent:
    configs:
      - source: daily_backup
        target: /etc/dockervolumebackup/conf.d/10-daily.conf
      - source: weekly_backup
        target: /etc/dockervolumebackup/conf.d/20-weekly.conf
      - source: monthly_backup
        target: /etc/dockervolumebackup/conf.d/30-monthly.conf
    extends:
      file: volume-backup.yaml
      service: aws-backup

  aws-backup-infrequent:
    configs:
      - source: biweekly_backup
        target: /etc/dockervolumebackup/conf.d/25-biweekly.conf
      - source: monthly_backup_shortterm
        target: /etc/dockervolumebackup/conf.d/30-monthly.conf
    extends:
      file: volume-backup.yaml
      service: aws-backup
